.TH NYANCAT 1
.SH NAME
nyancat \- command-line nyancat animation
.SH SYNOPSIS
.B nyancat
[\fB\-neh\fR] [\fB\-f\fR \fIframes\fR] [\fB\-W\fR \fIwidth\fR] [\fB\-H\fR \fIheight\fR]
.SH DESCRIPTION
.B nyancat
renders a loop of the nyancat animation while
playing the class nyancat music.
.SH OPTIONS
.TP
.B \-n, \-\-no\-counter
Do not display the timer
.TP
.B \-e, \-\-no\-clear
Do not clear the display betwen frames
.TP
.B \-f, \-\-frames=\fIFRAMES\fR
Display the requested number of frames, then quit
.TP
.B \-W, \-\-width=\fIWIDTH\fR
Crop the animation to the given width
.TP
.B \-H, \-\-height=\fIHEIGHT\fR
Crop the animation to the given height
.TP
.B \-h, \-\-help
Show the help message and exit
.SH AUTHOR
nyancat was written by MWPuppire.
It is released under the MIT license and freely available
on GitHub at https://github.com/mwpuppire/nyancat.
